# Generated by Django 5.1.2 on 2025-06-27 07:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tenant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('max_active_drivers', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('max_active_trucks', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('max_organizations', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('monthly_order_limit', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('monthly_license_limit', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('monthly_token_limit', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('storage_limit_mb', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_custom', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantCustomQuota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_active_drivers', models.IntegerField(blank=True, null=True)),
                ('max_active_trucks', models.IntegerField(blank=True, null=True)),
                ('max_organizations', models.IntegerField(blank=True, null=True)),
                ('monthly_order_limit', models.IntegerField(blank=True, null=True)),
                ('monthly_license_limit', models.IntegerField(blank=True, null=True)),
                ('monthly_token_limit', models.IntegerField(blank=True, null=True)),
                ('storage_limit_mb', models.IntegerField(blank=True, null=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsagePeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('orders_processed', models.IntegerField(default=0)),
                ('licenses_processed', models.IntegerField(default=0)),
                ('tokens_used', models.IntegerField(default=0)),
                ('storage_used_mb', models.IntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('feature', models.CharField(max_length=50)),
                ('tokens_used', models.IntegerField(default=0)),
                ('storage_delta_mb', models.FloatField(default=0.0)),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
                ('usage_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.usageperiod')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuotaAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('alert_type', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical'), ('exceeded', 'Exceeded')], max_length=20)),
                ('feature', models.CharField(max_length=50)),
                ('threshold_percentage', models.IntegerField()),
                ('message', models.TextField()),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
            ],
            options={
                'ordering': ['-notified_at'],
                'indexes': [models.Index(fields=['tenant', 'alert_type', 'feature'], name='subscriptio_tenant__778790_idx'), models.Index(fields=['acknowledged', 'notified_at'], name='subscriptio_acknowl_3ff709_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.subscriptionplan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tenant.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'is_active', 'start_date', 'end_date'], name='subscriptio_tenant__6b5bc0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='usageperiod',
            index=models.Index(fields=['tenant', 'start_date', 'end_date'], name='subscriptio_tenant__204ea9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usageperiod',
            unique_together={('tenant', 'start_date', 'end_date')},
        ),
    ]
