# Generated by Django 5.1.2 on 2025-06-27 07:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='The name of the organization', max_length=255, verbose_name='Organization Name')),
                ('address', models.TextField(help_text='Full address of the organization', verbose_name='Address')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=12.0, help_text='Default commission percentage for dispatches', max_digits=5, verbose_name='Commission Percentage')),
                ('commission_currency', models.CharField(choices=[('CAD', 'Canadian Dollar'), ('USD', 'US Dollar')], default='CAD', help_text='Default currency for commission amounts', max_length=3, verbose_name='Commission Currency')),
                ('carrier', models.OneToOneField(blank=True, help_text='Associated carrier', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization', to='fleet.carrier')),
                ('tenant', models.OneToOneField(help_text='Associated tenant', on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
    ]
