# Generated by Django 5.1.2 on 2025-06-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='tax_currency',
            field=models.CharField(choices=[('CAD', 'Canadian Dollar'), ('USD', 'US Dollar')], default='CAD', help_text='Currency for tax calculations', max_length=3, verbose_name='Tax Currency'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=13.0, help_text='Tax percentage rate for this carrier', max_digits=5, verbose_name='Tax Rate'),
        ),
    ]
