# Generated by Django 5.1.2 on 2025-06-27 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('dispatch', '0001_initial'),
        ('fleet', '0001_initial'),
        ('tenant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='carrier',
            field=models.ForeignKey(blank=True, help_text='Carrier handling this dispatch', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.carrier'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer for this dispatch', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.customer'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='Assigned driver', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.driver'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='tenant',
            field=models.ForeignKey(help_text='Associated tenant', on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='truck',
            field=models.ForeignKey(blank=True, help_text='Assigned truck', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.truck'),
        ),
        migrations.AddField(
            model_name='drivertruckassignment',
            name='carrier',
            field=models.ForeignKey(blank=True, help_text='The carrier assigned to the driver', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_carrier_assignments', to='fleet.carrier'),
        ),
        migrations.AddField(
            model_name='drivertruckassignment',
            name='dispatch',
            field=models.ForeignKey(blank=True, help_text='Associated dispatch if this is a dispatch-specific assignment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='dispatch.dispatch'),
        ),
        migrations.AddField(
            model_name='drivertruckassignment',
            name='driver',
            field=models.ForeignKey(help_text='The driver assigned to the truck', on_delete=django.db.models.deletion.CASCADE, related_name='truck_assignments', to='fleet.driver'),
        ),
        migrations.AddField(
            model_name='drivertruckassignment',
            name='tenant',
            field=models.ForeignKey(help_text='Associated tenant', on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='drivertruckassignment',
            name='truck',
            field=models.ForeignKey(help_text='The truck assigned to the driver', on_delete=django.db.models.deletion.CASCADE, related_name='driver_assignments', to='fleet.truck'),
        ),
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient_groups',
            field=models.ManyToManyField(blank=True, related_name='notifications', to='auth.group'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient_users',
            field=models.ManyToManyField(blank=True, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer associated with this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='fleet.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='order',
            field=models.ForeignKey(help_text='Order being dispatched', on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='dispatch.order'),
        ),
        migrations.AddField(
            model_name='orderlog',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderlog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='statushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statushistory',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='statushistory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='tenantsequence',
            name='tenant',
            field=models.ForeignKey(help_text='Associated tenant', on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='trip',
            name='order',
            field=models.ForeignKey(help_text='Order associated with this trip', on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='dispatch.order'),
        ),
        migrations.AddField(
            model_name='trip',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='trip',
            field=models.ForeignKey(blank=True, help_text='Associated trip details', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispatch.trip'),
        ),
        migrations.AddField(
            model_name='triplog',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='triplog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entries', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='triplog',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dispatch.trip'),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='dispatch.order'),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='drivertruckassignment',
            constraint=models.UniqueConstraint(fields=('driver', 'truck', 'start_date'), name='unique_driver_truck_assignment'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['content_type', 'object_id'], name='dispatch_no_content_f596f2_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type'], name='dispatch_no_type_62b768_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status'], name='dispatch_no_status_d35c9a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='dispatch_no_created_642378_idx'),
        ),
        migrations.AddIndex(
            model_name='statushistory',
            index=models.Index(fields=['content_type', 'object_id'], name='dispatch_st_content_ccb71b_idx'),
        ),
        migrations.AddIndex(
            model_name='statushistory',
            index=models.Index(fields=['changed_at'], name='dispatch_st_changed_2e0722_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantsequence',
            index=models.Index(fields=['tenant', 'sequence_type'], name='dispatch_te_tenant__e37bf9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantsequence',
            unique_together={('tenant', 'sequence_type')},
        ),
    ]
